### ISSUE TITLE
TypeError: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by crushedbits** [Achronite/node-red-contrib-energenie-ener314rt#49] opened 2021-04-27 18:02 UTC
Hi
I have recently bought the energenie ENER314rt board for the raspberry pi. I am just trying to control a blue socket with the module and node-red but I seem unable to get it to work.
I am using a newly installed pi, with node-red v1.3.3 I loaded your module using npm and can see all the blocks.
I can double click into the OOK blue block, learn and use the button in it to turn the socket on and off, but if I deploy a flow I receive the following error TypeError: Cannot read property 'log' of undefined
Now I may be new to node-red but I thought I could connect your OOK block to an inject block and just pass a boolean true to turn it on, have also tried a number 1 and a string 1. Am I just doing something wrong. I would be really grateful for some pointers.
I am trying to use the whole home energy monitor to monitor my solar panels and then using an OOK socket to turn on a washing machine.

**Comment by Achronite** [comment] 2021-04-28 09:02
Hi,

Sending a boolean type of true/false or a 1/0 into the node should be the same and both work equally.

Can you confirm the version of node-red-contrib-energenie-ener314rt that you are using and also send me the console log file?

A test flow would be good too; just select the nodes in question and chose 'export'.

**Comment by crushedbits** [comment] 2021-04-28 17:39
Thanks for getting back to me so quickly.
The version of node-red-contrib-energenie-ener314rt is 0.4.0
I captured a log file and have attached it as node-red.log
I have also attached the exported JSON.
Was not sure how to delete the Control&Monitor node, so what I did was disable it. Deleted the flow, restarted node-red, then remade the flow and ran it. Unfortunately the problem persists. I included the log of this in the same node-red.log file under the asterisks.

[node-red.log.txt](https://github.com/Achronite/node-red-contrib-energenie-ener314rt/files/6393726/node-red.log.txt)


Exported flow.

[{"id":"2fd4015e.729f5e","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"96ecf18e.9f994","type":"energenie-board","name":"ENER314-RT","timeout":"5000"},{"id":"fdab43dc.8d32e","type":"ook-switch","z":"2fd4015e.729f5e","name":"Control","zone":0,"switchNum":1,"board":"96ecf18e.9f994","x":600,"y":200,"wires":[[]],"inputLabels":["switch#1"]},{"id":"d2c65190.578d1","type":"inject","z":"2fd4015e.729f5e","name":"On","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":140,"y":180,"wires":[["fdab43dc.8d32e"]]},{"id":"e53ce858.945958","type":"inject","z":"2fd4015e.729f5e","name":"Off","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":140,"y":240,"wires":[["fdab43dc.8d32e"]]}]

**Comment by Achronite** [comment] 2021-04-28 18:09
OK I have a possible fix in my develop branch, that I would like you to test.

Assuming you are running this on rPi using standard install:

1) Download [ener314-rt.js](https://github.com/Achronite/node-red-contrib-energenie-ener314rt/blob/6c91b3dc72a99a95bf5ee6dc4780b7a532d7c3f1/red/ener314-rt.js)

2) node-red-stop

3) Replace the file ~/.node-red/node_modules/node-red-contrib-energenie-ener314rt/red/ener314-rt.js with the one downloaded

4) node-red-start

Please let me know how you get on.

**Comment by crushedbits** [comment] 2021-04-29 16:12
Hi,
Have tried replacing the ener314-rt.js file, unfortunately it is still displaying the same problem.
I have included a picture of the node-red work area showing that the control node still shows not configured and the console gives the same error. Have also included another log file and flow export.

Yes it is running on a rPi with a standard lite install.

JSON
[{"id":"2fd4015e.729f5e","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"e03e56f3.188558","type":"energenie-board","name":"ENER314-RT","timeout":"5000"},{"id":"12425b63.79c235","type":"ook-switch","z":"2fd4015e.729f5e","name":"Control","zone":0,"switchNum":1,"board":"e03e56f3.188558","x":510,"y":240,"wires":[[]]},{"id":"c577dceb.a1357","type":"inject","z":"2fd4015e.729f5e","name":"on","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":180,"y":160,"wires":[["12425b63.79c235"]]},{"id":"65b196f0.988268","type":"inject","z":"2fd4015e.729f5e","name":"off","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":160,"y":300,"wires":[["12425b63.79c235"]]}]
[node-red.log.txt](https://github.com/Achronite/node-red-contrib-energenie-ener314rt/files/6400031/node-red.log.txt)
![not_configured](https://user-images.githubusercontent.com/83167198/116582559-68a14300-a90d-11eb-919b-1a1399bf9c89.PNG)

**Comment by Achronite** [comment] 2021-04-29 16:48
The 'Not Configured' error occurs when you have not added an energenie board that it is associated with.  This is stored as a config node in the palette.  It could explain the TypeError too; the config node is somehow getting confused.

Check your 'Configuration Nodes' using the burger menu.  You should have **one** of type 'energenie-board', by default it is called 'ENER314-RT', and this should be selected within the Control Node under 'Board'. If you have multiple config nodes, delete all but one.

If you still have issues, delete all energenie nodes and the config node; redeploy to ensure everything is clean and then add the control node back, it should then only show 'Add new energenie board...' in the control node board dropdown, click on the pencil and add a board, then deploy.  You can do any teaching later.

In the log file you should then see a line that says '[info] ener314rt: radio initialised' when starting node-red.

**Comment by crushedbits** [comment] 2021-04-29 17:44
![1_all_nodes_deleted](https://user-images.githubusercontent.com/83167198/116594927-a9538900-a91a-11eb-8814-c42b7d9beebf.PNG)
![2_nodes_in_palette](https://user-images.githubusercontent.com/83167198/116594929-a9ec1f80-a91a-11eb-92b0-c98ddeef6644.PNG)
![3_add_new_energenie_board](https://user-images.githubusercontent.com/83167198/116594932-aa84b600-a91a-11eb-9075-6542137a01ff.PNG)
![4_add_new_board](https://user-images.githubusercontent.com/83167198/116594934-aa84b600-a91a-11eb-8a25-ece2ac172451.PNG)
![5_done](https://user-images.githubusercontent.com/83167198/116594935-ab1d4c80-a91a-11eb-81be-f87bac888279.PNG)
![6_control_node_in_workspace](https://user-images.githubusercontent.com/83167198/116594937-ab1d4c80-a91a-11eb-85b7-2b90f2c4e226.PNG)
![7_deployed_says_success_but_says_not_configured](https://user-images.githubusercontent.com/83167198/116594939-abb5e300-a91a-11eb-819c-b52e1bcd3910.png)
![8_ENER314-RT_under_configuration_node](https://user-images.githubusercontent.com/83167198/116594941-abb5e300-a91a-11eb-9735-b66822cddabd.PNG)

**Comment by crushedbits** [comment] 2021-04-29 17:56
Tried again. 

1. deleted all nodes
2. Selected control node
3. Double clicked it, pressed pencil
4. Pressed Add excepting all defaults
5. pressed done
6. deployed
7. Says successful but still gives not configured error
8. checked configuration node menu.

list relates to pictures above.

Could not find the info comment in the log but I am still getting this:
29 Apr 18:41:22 - [error] [energenie-board:1f07aa02.7ea0d6] TypeError: Cannot read property 'log' of undefined

It does kind of feel as if the board config is missing.  I do leave it all as default. I know your driver behind node-red is working as using the learn button turns it on and the off button turns the socket off.

**Comment by Achronite** [comment] 2021-04-29 20:20
The TypeError bug is caused by a log statement in energenie-board aka ener314-rt.js, by trying to access a variable 'out of scope', For example using 'this.log' within a function.  You are not seeing the radio inititalised message in the log file, so it is probably that statement causing the issue.

I suspect it is some weird bug that only occurs when OOK switches are added at initial config, I'll need to do some further testing on an old pi; as I dont want to mess with my home server setup with many devices.

In the meantime, can you comment out the line "use strict" within `ener314-rt.js`, this can sometimes be used to ignore these types of errors.

**Comment by Achronite** [comment] 2021-04-29 21:08
OK - I've done a bit more digging, it looks like the config node may not be created properly if there is an issue with the call to initialise the board; which could cause the 'Not Configured' message;  I've moved the node creation further up the code, please try this file: .  I've updated [ener314-rt.js](https://github.com/Achronite/node-red-contrib-energenie-ener314rt/blob/05c5d0a16f48eb89170161db1edef5f79cd145da/red/ener314-rt.js) - try this.

**Comment by crushedbits** [comment] 2021-05-03 09:37
Hi
You have cracked it. All now working well. Have managed to switch OOK switches and retrieve payload from whole house monitor. If you are still interested I am using a rPi3.
Thanks for sticking with it, you are a star.
I noticed that github allows BAT tipping. (Small triangle at top right of comment box) But you have not verified yourself as a content provider. If you are interested try reading this https://chrisruppel.com/blog/brave-rewards-github-pages/
Or going to Braves website and searching content creators. I think it would be worth doing because it makes tipping people like yourself really easy. If you do verify yourself let me know on this thread and I will bung you a few BAT. (At present 1 BAT = $1.18)
Again Thanks for your time.

**Closed** 2021-05-05 20:59 UTC
Labels: bug
